app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot(items = list(export = TRUE), screenshot = TRUE)

app$setInputs(Grocery_Listdt_rows_selected = 1, allowInputNoBinding_ = TRUE)
app$setInputs(Grocery_Listdt_rows_last_clicked = 1, allowInputNoBinding_ = TRUE)
app$setInputs(Grocery_List_edit = "click")
app$setInputs(Grocery_List_edit_Buy = "Teabags")
app$setInputs(Grocery_List_edit_Quantity = 2)
Sys.sleep(2)
app$setInputs(Grocery_List_update = "click")
app$setInputs(Grocery_Listdt_rows_selected = 2, allowInputNoBinding_ = TRUE)
app$setInputs(Grocery_Listdt_rows_last_clicked = 2, allowInputNoBinding_ = TRUE)
app$setInputs(Grocery_List_remove = "click")
Sys.sleep(2)
app$setInputs(Grocery_List_delete = "click")
app$setInputs(Grocery_Listdt_rows_selected = 3, allowInputNoBinding_ = TRUE)
app$setInputs(Grocery_Listdt_rows_last_clicked = 3, allowInputNoBinding_ = TRUE)
app$setInputs(Grocery_List_copy = "click")
app$setInputs(Grocery_List_add_Quantity = 5)
app$setInputs(Grocery_List_add_Buy = "Apples")
app$setInputs(Grocery_List_add_Buy = "Apple Cider")
Sys.sleep(2)
app$setInputs(Grocery_List_insert = "click")
app$setInputs(Grocery_List_add = "click")
app$setInputs(Grocery_List_add_Buy = "")
app$setInputs(Grocery_List_add_Buy = "Carrots")
app$setInputs(Grocery_List_add_Quantity = 7)
Sys.sleep(2)
app$setInputs(Grocery_List_insert = "click")
Sys.sleep(2)

app$snapshot(items = list(export = TRUE), screenshot = TRUE)
app$stop()